services:
  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: always

  frontend:
    build:
      context: app/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
