"""
Aggregate Property Data to DuckDB

This script scans for Parquet files generated by the property scraper,
loads them into a DuckDB database, and handles deduplication.
"""

import duckdb
import logging
import argparse
from pathlib import Path
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def setup_database(db_path: Path):
    """Initialize DuckDB connection and create schema if needed."""
    conn = duckdb.connect(str(db_path))
    
    # Create main properties table if it doesn't exist
    # We use a macro or just rely on CREATE TABLE AS SELECT for the first load
    # But to ensure types, it's better to let DuckDB infer from Parquet first
    
    return conn

def aggregate_data(
    input_dir: Path,
    db_path: Path,
    table_name: str = "properties",
    recreate: bool = False
):
    """
    Aggregate Parquet files into DuckDB.
    
    Args:
        input_dir: Directory containing Parquet files (recursive search)
        db_path: Path to DuckDB database file
        table_name: Name of the table to store properties
        recreate: If True, drop existing table and reload everything
    """
    # Find all parquet files
    parquet_files = sorted(list(input_dir.glob("**/*.parquet")))
    
    if not parquet_files:
        logger.warning(f"No parquet files found in {input_dir}")
        return
    
    logger.info(f"Found {len(parquet_files)} parquet files")
    
    conn = setup_database(db_path)
    
    try:
        # Create a view of all parquet files
        # DuckDB can read list of files
        files_str = [str(p) for p in parquet_files]
        
        # If recreate is requested, drop the table
        if recreate:
            logger.info(f"Dropping table {table_name}...")
            conn.execute(f"DROP TABLE IF EXISTS {table_name}")
        
        # Check if table exists
        table_exists = False
        try:
            conn.execute(f"SELECT 1 FROM {table_name} LIMIT 1")
            table_exists = True
        except duckdb.CatalogException:
            table_exists = False
            
        if not table_exists:
            logger.info(f"Creating table {table_name} from {len(parquet_files)} files...")
            # Create table with deduplication logic built-in? 
            # Or just load raw and then deduplicate?
            # Let's load raw first into a temp table/view then insert/replace
            
            # We want to keep the LATEST version of each property_id
            query = f"""
            CREATE TABLE {table_name} AS 
            SELECT * FROM read_parquet({files_str})
            QUALIFY ROW_NUMBER() OVER (PARTITION BY property_id ORDER BY scraped_at DESC) = 1
            """
            conn.execute(query)
            logger.info(f"Created {table_name} with {conn.execute(f'SELECT COUNT(*) FROM {table_name}').fetchone()[0]} rows")
            
        else:
            logger.info(f"Updating {table_name}...")
            # Create temp table for new data
            conn.execute("CREATE OR REPLACE TEMP TABLE new_data AS SELECT * FROM read_parquet(?)", [files_str])
            
            # Upsert logic:
            # 1. Delete existing rows that are in new_data
            # 2. Insert new_data
            # This is simpler than complex MERGE for now, assuming property_id is unique key
            
            # However, we only want to update if scraped_at is newer?
            # Or just blindly trust the new batch?
            # Let's trust the new batch but only if we actually have new data.
            
            # Better approach for "add to database":
            # 1. Load all parquet files into a temp table
            # 2. Union with existing table
            # 3. Deduplicate keeping latest
            # 4. Replace table
            
            # But that's heavy for large existing DB.
            # Let's assume we want to MERGE.
            
            # For now, let's stick to the "Rebuild" approach if it's fast enough (DuckDB usually is),
            # OR just append and dedupe later.
            
            # Let's try a Merge-like approach:
            # Delete rows from main table that exist in new files
            conn.execute(f"""
            DELETE FROM {table_name} 
            WHERE property_id IN (SELECT property_id FROM new_data)
            """)
            
            # Insert new rows
            conn.execute(f"INSERT INTO {table_name} SELECT * FROM new_data")
            
            # Final dedupe just in case (self-correction)
            # This might be expensive, so maybe skip if we trust the inputs
            
            logger.info(f"Updated {table_name}. Total rows: {conn.execute(f'SELECT COUNT(*) FROM {table_name}').fetchone()[0]}")
            
    except Exception as e:
        logger.error(f"Error aggregating data: {e}")
        raise
    finally:
        conn.close()

def main():
    parser = argparse.ArgumentParser(description="Aggregate property data to DuckDB")
    parser.add_argument("--input", "-i", type=Path, default=Path("data/processed/property_details/gha_runs"), help="Input directory containing Parquet files")
    parser.add_argument("--db", "-d", type=Path, default=Path("data/database/properties.duckdb"), help="Path to DuckDB database")
    parser.add_argument("--recreate", action="store_true", help="Recreate table from scratch")
    
    args = parser.parse_args()
    
    # Ensure directories exist
    if not args.input.exists():
        logger.error(f"Input directory {args.input} does not exist")
        return
        
    args.db.parent.mkdir(parents=True, exist_ok=True)
    
    aggregate_data(args.input, args.db, recreate=args.recreate)

if __name__ == "__main__":
    main()
